<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DkplusControllerDsl\Dsl\Container'              => __DIR__ . '/src/DkplusControllerDsl/Dsl/Container.php',
    'DkplusControllerDsl\Dsl\ContainerInterface'     => __DIR__ . '/src/DkplusControllerDsl/Dsl/ContainerInterface.php',
    'DkplusControllerDsl\Dsl\Dsl'                    => __DIR__ . '/src/DkplusControllerDsl/Dsl/Dsl.php',
    'DkplusControllerDsl\Dsl\DslInterface'           => __DIR__ . '/src/DkplusControllerDsl/Dsl/DslInterface.php',
    'DkplusControllerDsl\Dsl\Executor'               => __DIR__ . '/src/DkplusControllerDsl/Dsl/Executor.php',
    'DkplusControllerDsl\Dsl\ExecutorInterface'      => __DIR__ . '/src/DkplusControllerDsl/Dsl/ExecutorInterface.php',
    'DkplusControllerDsl\Dsl\Phrase\PhraseInterface' => __DIR__ . '/src/DkplusControllerDsl/Dsl/Phrase/PhraseInterface.php',
    'DkplusControllerDsl\PhraseManager'              => __DIR__ . '/src/DkplusControllerDsl/Dsl/Phrase/PhraseManager.php',
    'DkplusControllerDsl\Module'                     => __DIR__ . '/src/DkplusControllerDsl/Module.php',
);