<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DkplusControllerDsl\Controller\Plugin\Dsl'                => __DIR__ . '/src/DkplusControllerDsl/Controller/Plugin/Dsl.php',
    'DkplusControllerDsl\Dsl\Container'                        => __DIR__ . '/src/DkplusControllerDsl/Dsl/Container.php',
    'DkplusControllerDsl\Dsl\ContainerInterface'               => __DIR__ . '/src/DkplusControllerDsl/Dsl/ContainerInterface.php',
    'DkplusControllerDsl\Dsl\Dsl'                              => __DIR__ . '/src/DkplusControllerDsl/Dsl/Dsl.php',
    'DkplusControllerDsl\Dsl\DslInterface'                     => __DIR__ . '/src/DkplusControllerDsl/Dsl/DslInterface.php',
    'DkplusControllerDsl\Dsl\Executor'                         => __DIR__ . '/src/DkplusControllerDsl/Dsl/Executor.php',
    'DkplusControllerDsl\Dsl\ExecutorInterface'                => __DIR__ . '/src/DkplusControllerDsl/Dsl/ExecutorInterface.php',
    'DkplusControllerDsl\Dsl\Phrase\ExecutablePhraseInterface' => __DIR__ . '/src/DkplusControllerDsl/Dsl/Phrase/ExecutablePhraseInterface.php',
    'DkplusControllerDsl\Dsl\Phrase\PhraseInterface'           => __DIR__ . '/src/DkplusControllerDsl/Dsl/Phrase/PhraseInterface.php',
    'DkplusControllerDsl\Dsl\Phrase\PhraseManager'             => __DIR__ . '/src/DkplusControllerDsl/Dsl/Phrase/PhraseManager.php',
    'DkplusControllerDsl\Dsl\Phrase\PostPhraseInterface'       => __DIR__ . '/src/DkplusControllerDsl/Dsl/Phrase/PostPhraseInterface.php',
    'DkplusControllerDsl\Dsl\Phrase\PrePhraseInterface'        => __DIR__ . '/src/DkplusControllerDsl/Dsl/Phrase/PrePhraseInterface.php',
    'DkplusControllerDsl\Dsl\PrePostExecutorDecorator'         => __DIR__ . '/src/DkplusControllerDsl/Dsl/PrePostExecutorDecorator.php',
    'DkplusControllerDsl\Module'                               => __DIR__ . '/src/DkplusControllerDsl/Module.php',
);